### ISSUE TITLE
Extension is not working

### ISSUE THREAD

**Issue by luandknguyen** [suitangi/TwitchEmotesMessenger#4]
I just installed this extension, and it is not working for me. I mess around a bit and found out that changing line 177 in `index.js` from:

```javascript
  if (document.querySelectorAll('[data-testid="messenger_incoming_text_row"]').length + document.querySelectorAll('[data-testid="outgoing_message"]').length > 0) {
```

to:

```javascript
  if (document.querySelectorAll('[data-testid="message-container"]').length > 0) {
```

works for me.

I do not know why, but I guess that Messenger changed its `data-testid` from `messenger_incoming_text_row` to `message-container` so the extension broke.

**Comment by suitangi** [comment]
Hi I haven't looked at this repo in a while. Thanks for letting me know! I've updated the extension.
